services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app/index.php:/var/www/html/index.php
      - ./app/images:/var/www/html/images
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: app/Dockerfile-php
    volumes:
      - ./app/index.php:/var/www/html/index.php
      - ./app/images:/var/www/html/images
    depends_on:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: database/Dockerfile-mysql
    ports:
      - "3306:3306"
